'use strict';
const $=id=>document.getElementById(id);
const SHELL_SCHEMA='ikant-advanced-web-shell/v0.26-test',SHELL_COMMAND_SCHEMA='ikant-advanced-web-shell-command/v0.26-test',SHELL_ACK_SCHEMA='ikant-advanced-web-shell-ack/v0.26-test',WEB_FRAME_SCHEMA='ikant-web-human-frame/v0.20-test',WEB_ACK_SCHEMA='ikant-web-human-ack/v0.20-test',PRODUCT_SCHEMA='ikant-product-experience/v0.27-test',PRODUCT_VOICE_SCHEMA='ikant-product-voice-candidate/v0.27-test',EXPERIENCE_SCHEMA='ikant-experience-projection/v1.3';
const IKANT_PENDING_PRIMARY='iKant: [PENDING - la risposta validata non e ancora stata emessa]',IKANT_RUNTIME_EVENT_LIMIT=48,IKANT_VOICE_MEDIA_TYPES=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus','audio/webm','audio/ogg'],IKANT_VOICE_MEDIA_BASES=new Set(['audio/webm','audio/mp4','audio/ogg','audio/wav','audio/x-wav','audio/mpeg']);
const clientId=sessionStorage.getItem('ikantShellClient')||randomId('client');sessionStorage.setItem('ikantShellClient',clientId);
const state={token:sessionStorage.getItem('ikantBearer')||'',frame:null,shell:null,recovering:false,product:null,view:'conversation',voiceOutput:false,recognition:null,recording:null,setupTimer:null,runtimeEvents:[],turnStarted:0,turnWatchdogs:[]};
function randomId(prefix){if(!window.crypto||!crypto.getRandomValues)throw new Error('secure browser randomness unavailable');if(crypto.randomUUID)return prefix+'-'+crypto.randomUUID();const b=new Uint8Array(18);crypto.getRandomValues(b);return prefix+'-'+Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');}
function show(id,on=true){const el=$(id);if(el)el.hidden=!on;} function text(id,v){const el=$(id);if(el)el.textContent=String(v??'');}
function safeMessage(v){return String(v||'errore').replace(/Bearer\s+\S+/gi,'Bearer [REDACTED]').replace(/((?:token|password|secret|api[_-]?key)\s*[:=]\s*)\S+/gi,'$1[REDACTED]').replace(/[\u0000-\u001f\u007f]+/g,' ').trim().slice(0,240);}
function runtimeEvent(kind,detail={}){const e={seq:(state.runtimeEvents.at(-1)?.seq||0)+1,at:new Date().toISOString(),kind,detail,epistemic_authority:0.0,execution_authority:0.0};state.runtimeEvents.push(e);if(state.runtimeEvents.length>IKANT_RUNTIME_EVENT_LIMIT)state.runtimeEvents.splice(0,state.runtimeEvents.length-IKANT_RUNTIME_EVENT_LIMIT);renderDiagnostics();return e;}
function setStatus(label,mode=''){text('status-label',label);const d=$('status-dot');if(d)d.className='status-dot'+(mode?' '+mode:'');}
function setEntity(label,mode='ready'){const e=$('entity');if(!e)return;e.dataset.state=mode;e.setAttribute('aria-label',label);text('shell-status',label);}
async function api(path,{method='GET',body=null,raw=null,contentType='application/json',headers={}}={}){const h={...headers};if(state.token)h.Authorization='Bearer '+state.token;if(raw!==null)h['Content-Type']=contentType;else if(body!==null)h['Content-Type']='application/json';let r;try{r=await fetch(path,{method,headers:h,body:raw!==null?raw:(body!==null?JSON.stringify(body):undefined),cache:'no-store'});}catch(e){runtimeEvent('HTTP_TRANSPORT_ERROR',{path,message:safeMessage(e.message)});throw e;}const rawText=await r.text();let p={};if(rawText){try{p=JSON.parse(rawText);}catch(_){p={error:rawText};}}if(!r.ok){const e=new Error(safeMessage(p.error||p.message||('HTTP '+r.status)));e.status=r.status;runtimeEvent('HTTP_ERROR',{path,status:r.status,message:e.message});throw e;}return p;}
function retryable(e){const s=Number(e?.status||0);return !s||s===408||s===425||s===429||s>=500;} async function apiRetry(path,o){try{return await api(path,o);}catch(e){if(!retryable(e))throw e;runtimeEvent('HTTP_RETRY',{path});return api(path,o);}}
function pairedUI(on){show('pair-panel',!on);show('pair-reset',on);} async function pair(code){const p=await api('/api/v1/pair',{method:'POST',body:{code}});state.token=p.bearer_token;sessionStorage.setItem('ikantBearer',state.token);history.replaceState(null,'',location.pathname+location.search);pairedUI(true);await productLoop(true);}
async function productStatus(){const out=await api('/api/v3/product/status');if(out?.schema!==PRODUCT_SCHEMA)throw new Error('stato prodotto non valido');state.product=out;renderProduct(out);return out;}
function renderProduct(out){const stage=String(out.stage||'STARTING');const busy=['STARTING','PREPARING'].includes(stage);setStatus(stage==='READY'?'Pronto':stage==='BLOCKED'?'Bloccato':'Preparazione',stage==='READY'?'ready':stage==='BLOCKED'?'blocked':'busy');const p=out.progress||{},frac=typeof p.fraction==='number'?Math.max(0,Math.min(1,p.fraction)):null,pct=frac===null?null:Math.round(frac*100);text('setup-phase',stage==='BLOCKED'?'Bloccato':stage==='READY'?'Pronto':'Preparazione');text('setup-target',p.target||'');text('setup-percent',pct===null?'—':pct+'%');if($('setup-bar'))$('setup-bar').style.width=(pct===null?(busy?18:0):pct)+'%';if($('setup-ring'))$('setup-ring').style.setProperty('--progress',(pct===null?(busy?18:0):pct)+'%');text('setup-diagnostics',JSON.stringify({stage,attempt:out.attempt,progress:p,diagnostics:out.diagnostics,voice:out.voice},null,2));show('setup-retry',stage==='BLOCKED');if(stage!=='READY'){show('setup-panel',true);show('admission-panel',false);show('active-panel',false);}renderDiagnostics();}
async function productLoop(immediate=false){clearTimeout(state.setupTimer);try{const out=await productStatus();if(out.runtime_ready){show('setup-panel',false);await refreshReady();return;}}catch(e){if(!state.token){pairedUI(false);return;}text('setup-diagnostics',safeMessage(e.message));}state.setupTimer=setTimeout(()=>productLoop(),immediate?350:900);}
async function refreshReady(){try{const l=await api('/api/v1/state');if(l.state==='ACTIVE')await loadActive();else await loadAdmission(l);}catch(e){show('setup-panel',true);text('setup-diagnostics',safeMessage(e.message));state.setupTimer=setTimeout(()=>productLoop(),900);}}
function updateSteps(l){const s=l.state;for(const [id,done] of [['step-accept',['ACCEPTED','PROBED','ACTIVE'].includes(s)],['step-probe',['PROBED','ACTIVE'].includes(s)],['step-init',s==='ACTIVE']])$(id)?.classList.toggle('done',done);$('probe-button').disabled=!['ACCEPTED','PROBED'].includes(s);$('init-button').disabled=s!=='PROBED';$('accept-text').disabled=s!=='AWAITING_ACCEPTANCE';}
async function loadAdmission(l){state.shell=null;show('active-panel',false);show('setup-panel',false);show('admission-panel',true);show('released-panel',false);const a=await api('/api/v1/admission');text('terms',a.terms);text('terms-digest',a.terms_sha256);updateSteps(l);text('preactive-status',JSON.stringify({state:l.state,model:l.model,voice:l.voice},null,2));setStatus('Accesso','ready');}
function primaryText(frame){const v=String(frame?.primary_text||'').trim();return v||IKANT_PENDING_PRIMARY;} function renderPrimaryFrame(frame){const value=primaryText(frame);text('dashboard',value);$('dashboard')?.classList.toggle('pending',value===IKANT_PENDING_PRIMARY);show('empty-state',!value);state.frame=frame;runtimeEvent('PRIMARY_DELIVERED',{elapsed_ms:state.turnStarted?Math.round(performance.now()-state.turnStarted):null});}
function buildWebAck(frame){const r=frame.receipt||{};return {schema:WEB_ACK_SCHEMA,runtime_session_id:r.runtime_session_id,epoch:r.epoch,frame_seq:r.frame_seq,frame_sha256:r.frame_sha256,visible_text:String(frame.text||''),visible_text_sha256:r.frame_sha256,epistemic_authority:0.0,execution_authority:0.0};}
async function renderLegacyFrame(frame){if(frame?.schema!==WEB_FRAME_SCHEMA)throw new Error('frame non valido');renderPrimaryFrame(frame);await apiRetry('/api/v1/frame/ack',{method:'POST',body:buildWebAck(frame)});runtimeEvent('ACK_DONE',{});await refreshExperience();}
function bindShell(o){if(o?.schema!==SHELL_SCHEMA||o.client_id!==clientId||!o.shell_id)throw new Error('connessione sessione fallita');state.shell={shell_id:o.shell_id,client_id:clientId,next_seq:o.next_seq,last_acked_frame:o.last_acked_frame||null};}
function freezeActive(on=true){for(const id of ['intent','send-button','exit-button','voice-button'])if($(id))$(id).disabled=on;} function released(on){show('released-panel',on);if(on)freezeActive(true);}
function renderTrace(trace){const host=$('cognitive-trace');if(!host)return;host.replaceChildren();for(const s of trace?.stages||[]){const row=document.createElement('div');row.className='trace-step';const facts=Object.entries(s.facts||{}).filter(([,v])=>v!==null&&v!==''&&v!==false).slice(0,2).map(([k,v])=>`${k.replaceAll('_',' ')} ${v}`).join(' · ');row.innerHTML=`<strong>${escapeHTML(s.label||s.id)}</strong><small>${escapeHTML(facts)}</small>`;host.appendChild(row);}}
function escapeHTML(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function refreshExperience(){try{const x=await api('/api/v6/experience');if(x?.schema!==EXPERIENCE_SCHEMA)return;setEntity(x.state||'Pronto',x.state==='Pronto'?'ready':'busy');renderTrace(x.trace);text('turn-timing',JSON.stringify(x.timing||{},null,2));if(x.primary_text&&!String($('dashboard')?.textContent||'').trim())text('dashboard',x.primary_text);}catch(e){runtimeEvent('EXPERIENCE_REFRESH_FAIL',{message:safeMessage(e.message)});}}
async function renderShellResponse(r){if(r?.schema!==SHELL_SCHEMA)throw new Error('risposta sessione non valida');if(r.status==='RELEASED'&&r.frame===null){state.shell.next_seq=r.next_seq;state.shell.last_acked_frame=r.last_acked_frame||state.shell.last_acked_frame;setEntity('Sessione chiusa','ready');released(true);return r;}const f=r.frame;if(f?.schema!==WEB_FRAME_SCHEMA)throw new Error('frame mancante');renderPrimaryFrame(f);released(false);const op=r.operation||{},ack={schema:SHELL_ACK_SCHEMA,shell_id:state.shell.shell_id,client_id:clientId,seq:op.seq,idempotency_key:op.idempotency_key,frame_ack:buildWebAck(f)};const c=await apiRetry('/api/v2/shell/ack',{method:'POST',body:ack});if(c?.schema!==SHELL_SCHEMA||c.acknowledged!==true)throw new Error('conferma frame fallita');state.shell.next_seq=c.next_seq;state.shell.last_acked_frame=c.last_acked_frame||null;runtimeEvent('ACK_DONE',{elapsed_ms:state.turnStarted?Math.round(performance.now()-state.turnStarted):null});setEntity(c.status==='RELEASED'?'Sessione chiusa':'Pronto','ready');released(c.status==='RELEASED');freezeActive(false);maybeSpeak(f);await refreshExperience();return c;}
async function shellCommand(op,payload={}){if(!state.shell)throw new Error('sessione non aperta');freezeActive(true);setEntity(op==='TURN'?'Sto lavorando':'Connessione','busy');const cmd={schema:SHELL_COMMAND_SCHEMA,shell_id:state.shell.shell_id,client_id:clientId,seq:state.shell.next_seq,op,idempotency_key:randomId('op'),expected_frame:state.shell.last_acked_frame,payload};return renderShellResponse(await apiRetry('/api/v2/shell/command',{method:'POST',body:cmd}));}
async function openShell({synchronize=true}={}){freezeActive(true);setEntity('Connessione','busy');const o=await apiRetry('/api/v2/shell/open',{method:'POST',body:{client_id:clientId}});bindShell(o);if(o.pending_response){await renderShellResponse(o.pending_response);return;}if(synchronize)await shellCommand('SYNC',{});else{setEntity('Pronto','ready');freezeActive(false);}}
async function recoverShell(cause=null){if(state.recovering)return;state.recovering=true;setEntity('Ripristino','busy');runtimeEvent('SHELL_RECOVERY_START',{message:safeMessage(cause?.message)});try{await openShell({synchronize:true});runtimeEvent('SHELL_RECOVERY_PASS',{});}catch(e){setEntity('Bloccato','blocked');text('composer-hint','Connessione locale bloccata.');runtimeEvent('SHELL_RECOVERY_FAIL',{message:safeMessage(e.message)});}finally{state.recovering=false;}}
async function loadActive(){show('setup-panel',false);show('admission-panel',false);show('active-panel',true);show('pair-panel',false);show('pair-reset',true);setStatus('Pronto','ready');await openShell({synchronize:true});$('intent').focus();await refreshExperience();}
function openInspector(view='conversation'){state.view=view;$('active-panel').classList.add('inspector-open');$('inspector').setAttribute('aria-hidden','false');$('inspector-button').setAttribute('aria-expanded','true');$('status-button').setAttribute('aria-expanded','true');for(const b of document.querySelectorAll('[data-inspector-view]'))b.classList.toggle('active',b.dataset.inspectorView===view);show('inspector-overview',view==='conversation');show('inspector-artifacts',view==='artifacts');show('inspector-inspect',view==='inspect');show('inspector-system',view==='system');text('inspector-title',view==='artifacts'?'Tracce':view==='system'?'Diagnostica':'Dettagli');if(view==='artifacts')window.ikantTrace?.loadIndex?.();}
function closeInspector(){$('active-panel').classList.remove('inspector-open');$('inspector').setAttribute('aria-hidden','true');$('inspector-button').setAttribute('aria-expanded','false');$('status-button').setAttribute('aria-expanded','false');$('intent')?.focus();}
function renderDiagnostics(){text('system-diagnostics',JSON.stringify({runtime_live:{events:state.runtimeEvents.slice(-48),event_limit:48,epistemic_authority:0.0,execution_authority:0.0},product:state.product||null},null,2));text('voice-diagnostics',JSON.stringify({configured:state.product?.voice?.configured||false,events:state.runtimeEvents.filter(e=>e.kind.startsWith('VOICE_')).slice(-16)},null,2));}
function clearWatchdogs(){for(const t of state.turnWatchdogs)clearTimeout(t);state.turnWatchdogs=[];} function startWatchdogs(){clearWatchdogs();state.turnWatchdogs.push(setTimeout(()=>{setEntity('Sto lavorando','busy');runtimeEvent('TURN_WAITING',{elapsed_ms:4000});},4000));state.turnWatchdogs.push(setTimeout(()=>{setEntity('Più lento del solito','busy');runtimeEvent('TURN_SLOW',{elapsed_ms:20000});},20000));}
function localVoices(){return ('speechSynthesis'in window)?speechSynthesis.getVoices().filter(v=>v.localService===true):[];} function maybeSpeak(frame){if(!state.voiceOutput||frame?.receipt?.kind!=='TURN')return;const spoken=String(frame?.primary_text||'').replace(/^iKant:\s*/,'').trim();const voices=localVoices();if(!spoken||!voices.length)return;const u=new SpeechSynthesisUtterance(spoken);u.voice=voices[0];speechSynthesis.cancel();speechSynthesis.speak(u);}
function preferredVoiceMime(){if(typeof MediaRecorder==='undefined'||typeof MediaRecorder.isTypeSupported!=='function')return '';return IKANT_VOICE_MEDIA_TYPES.find(t=>MediaRecorder.isTypeSupported(t))||'';}
async function loopbackVoiceInput(){if(state.product?.voice?.configured!==true)throw new Error('STT locale non configurato');if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'||!state.shell)throw new Error('registrazione locale non disponibile');const stream=await navigator.mediaDevices.getUserMedia({audio:true}),chunks=[],mime=preferredVoiceMime();let rec;try{rec=mime?new MediaRecorder(stream,{mimeType:mime}):new MediaRecorder(stream);}catch(e){for(const t of stream.getTracks())t.stop();throw e;}const base=String(rec.mimeType||mime||'').split(';',1)[0].toLowerCase();if(base&&!IKANT_VOICE_MEDIA_BASES.has(base)){for(const t of stream.getTracks())t.stop();throw new Error('formato audio locale non supportato');}state.recording=rec;$('voice-button').setAttribute('aria-pressed','true');setEntity('Ascolto','busy');runtimeEvent('VOICE_RECORD_START',{mime:String(rec.mimeType||mime||'browser-default')});rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};rec.onerror=e=>runtimeEvent('VOICE_RECORD_ERROR',{message:safeMessage(e?.error?.message||e?.error)});rec.onstop=async()=>{for(const t of stream.getTracks())t.stop();state.recording=null;$('voice-button').setAttribute('aria-pressed','false');setEntity('Trascrivo','busy');const blob=new Blob(chunks,{type:rec.mimeType||mime||'audio/webm'});if(!blob.size){setEntity('Pronto','ready');text('composer-hint','Nessun audio rilevato.');return;}try{const out=await api('/api/v3/voice/transcribe',{method:'POST',raw:blob,contentType:blob.type||'audio/webm',headers:{'X-iKant-Shell-Id':state.shell.shell_id,'X-iKant-Client-Id':clientId}});if(out?.schema!==PRODUCT_VOICE_SCHEMA||out.auto_submit!==false||!String(out.text||'').trim())throw new Error('trascrizione locale non valida');$('intent').value=out.text;resizeComposer();$('intent').focus();text('composer-hint','');runtimeEvent('VOICE_TRANSCRIBE_PASS',{chars:String(out.text).length,auto_submit:false});}finally{setEntity('Pronto','ready');}};rec.start();setTimeout(()=>{if(state.recording===rec&&rec.state==='recording')rec.stop();},8000);}
async function toggleVoice(){if(state.recording){state.recording.stop();return;}if(state.recognition){state.recognition.stop();return;}const SR=window.SpeechRecognition;if(SR&&typeof SR.available==='function'){const lang=navigator.language||'it-IT';let a;try{a=await SR.available({langs:[lang],processLocally:true});}catch(e){runtimeEvent('VOICE_NATIVE_PROBE_FAIL',{message:safeMessage(e.message)});a='unavailable';}if(a==='downloadable'&&typeof SR.install==='function'){try{const installed=await SR.install({langs:[lang],processLocally:true});if(installed===true)a=await SR.available({langs:[lang],processLocally:true});}catch(e){runtimeEvent('VOICE_NATIVE_INSTALL_FAIL',{message:safeMessage(e.message)});a='unavailable';}}if(a==='available'){const r=new SR();r.lang=lang;r.processLocally=true;r.continuous=false;r.interimResults=true;state.recognition=r;r.onstart=()=>{setEntity('Ascolto','busy');$('voice-button').setAttribute('aria-pressed','true');runtimeEvent('VOICE_NATIVE_START',{lang});};r.onresult=e=>{let v='';for(let i=e.resultIndex;i<e.results.length;i++)v+=e.results[i][0].transcript;if(v.trim()){$('intent').value=v;resizeComposer();runtimeEvent('VOICE_NATIVE_RESULT',{chars:v.length});}};r.onerror=e=>runtimeEvent('VOICE_NATIVE_ERROR',{code:String(e.error||'error')});r.onend=()=>{state.recognition=null;$('voice-button').setAttribute('aria-pressed','false');setEntity('Pronto','ready');};r.start();return;}}if(state.product?.voice?.configured===true){await loopbackVoiceInput();return;}text('composer-hint','Voce locale non disponibile.');runtimeEvent('VOICE_UNAVAILABLE',{loopback_configured:false});}
function resizeComposer(){const e=$('intent');e.style.height='auto';e.style.height=Math.min(160,Math.max(42,e.scrollHeight))+'px';}
function openPalette(){const d=$('command-palette');if(!d.open)d.showModal();$('command-search').value='';$('command-search').focus();} function filterCommands(q){q=String(q||'').toLowerCase();for(const b of document.querySelectorAll('#command-list button'))b.hidden=!b.textContent.toLowerCase().includes(q);} async function runCommand(c){$('command-palette').close();if(c==='focus')$('intent').focus();if(c==='voice')await toggleVoice();if(c==='inspect')openInspector('conversation');if(c==='system')openInspector('system');if(c==='exit')await shellCommand('EXIT',{});}
$('pair-form').addEventListener('submit',async e=>{e.preventDefault();text('pair-error','');try{await pair($('pair-code').value.trim());}catch(x){text('pair-error',safeMessage(x.message));}});$('pair-reset').addEventListener('click',()=>{state.token='';state.shell=null;sessionStorage.removeItem('ikantBearer');location.reload();});$('setup-retry').addEventListener('click',async()=>{try{await api('/api/v3/product/retry',{method:'POST',body:{}});await productLoop(true);}catch(e){text('setup-diagnostics',safeMessage(e.message));}});$('terms-toggle').addEventListener('click',()=>{const t=$('terms');t.hidden=!t.hidden;text('terms-toggle',t.hidden?'Mostra':'Nascondi');});$('accept-form').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/v1/accept',{method:'POST',body:{phrase:$('accept-text').value,presented_terms_sha256:$('terms-digest').textContent}});await refreshReady();}catch(x){text('preactive-status',safeMessage(x.message));}});$('probe-button').addEventListener('click',async()=>{try{text('preactive-status',JSON.stringify(await api('/api/v1/probe',{method:'POST',body:{}}),null,2));await refreshReady();}catch(x){text('preactive-status',safeMessage(x.message));}});$('init-button').addEventListener('click',async()=>{try{const f=await api('/api/v1/initialize',{method:'POST',body:{}});show('admission-panel',false);show('active-panel',true);try{await renderLegacyFrame(f);}catch(_){}await openShell({synchronize:true});}catch(_){await refreshReady();}});
$('turn-form').addEventListener('submit',async e=>{e.preventDefault();const v=$('intent').value;if(!v.trim())return;state.turnStarted=performance.now();text('dashboard',IKANT_PENDING_PRIMARY);$('dashboard').classList.add('pending');text('composer-hint','');startWatchdogs();try{await shellCommand('TURN',{text:v});$('intent').value='';resizeComposer();$('intent').focus();}catch(x){text('composer-hint','Turno non completato.');await recoverShell(x);}finally{clearWatchdogs();}});$('intent').addEventListener('input',resizeComposer);$('intent').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();$('turn-form').requestSubmit();}});$('voice-button').addEventListener('click',()=>toggleVoice().catch(e=>{runtimeEvent('VOICE_TOGGLE_FAIL',{message:safeMessage(e.message)});text('composer-hint','Voce locale non disponibile.');}));$('voice-output-toggle').addEventListener('click',()=>{state.voiceOutput=!state.voiceOutput;$('voice-output-toggle').setAttribute('aria-pressed',String(state.voiceOutput));if(!state.voiceOutput&&'speechSynthesis'in window)speechSynthesis.cancel();});$('exit-button').addEventListener('click',()=>shellCommand('EXIT',{}).catch(recoverShell));$('resume-button').addEventListener('click',()=>shellCommand('RESUME',{}).catch(recoverShell));$('inspector-button').addEventListener('click',()=>$('active-panel').classList.contains('inspector-open')?closeInspector():openInspector('conversation'));$('status-button').addEventListener('click',()=>openInspector('system'));$('inspector-close').addEventListener('click',closeInspector);$('brand-button').addEventListener('click',()=>{$('intent')?.focus();});for(const b of document.querySelectorAll('[data-inspector-view]'))b.addEventListener('click',()=>openInspector(b.dataset.inspectorView));$('command-button').addEventListener('click',openPalette);$('command-search').addEventListener('input',e=>filterCommands(e.target.value));for(const b of document.querySelectorAll('#command-list button'))b.addEventListener('click',()=>runCommand(b.dataset.command));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette();}if(e.key==='Escape'&&$('active-panel').classList.contains('inspector-open'))closeInspector();});
if('speechSynthesis'in window)speechSynthesis.onvoiceschanged=()=>{show('voice-output-toggle',localVoices().length>0);};if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});const hash=new URLSearchParams(location.hash.replace(/^#/,'')),code=hash.get('pair');if(code){$('pair-code').value=code;pair(code).catch(e=>text('pair-error',safeMessage(e.message)));}else if(state.token){pairedUI(true);productLoop(true);}else{pairedUI(false);setStatus('Connetti','');}
