'use strict';
const BOOTSTRAP_STATUS_SCHEMA='ikant-bootstrap-observability/v0.29-test';
function bootstrapEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function ensureBootstrapSurface(){
 if($('bootstrap-journey'))return;const setup=$('setup-panel')?.querySelector('.setup-main');if(!setup)return;
 const box=document.createElement('section');box.id='bootstrap-journey';box.className='bootstrap-journey';box.setAttribute('aria-label','Diagnostica bootstrap');box.innerHTML='<div class="bootstrap-head"><div><small>BOOTSTRAP AUDIT</small><strong id="bootstrap-title">Diagnostica runtime</strong></div><span id="bootstrap-integrity" class="bootstrap-badge">journal</span></div><div id="bootstrap-alert" class="bootstrap-alert" role="alert" hidden></div><ol id="bootstrap-steps" class="bootstrap-steps"></ol><div class="bootstrap-actions"><button id="bootstrap-raw-toggle" class="secondary" type="button">Mostra log raw</button><button id="bootstrap-download" class="text-button" type="button">Scarica .jsonl</button></div><pre id="bootstrap-raw" class="bootstrap-raw" hidden></pre>';const disclosure=setup.querySelector('.disclosure');setup.insertBefore(box,disclosure||null);
 const admission=$('admission-panel')?.querySelector('.admission-card');if(admission){const d=document.createElement('details');d.id='bootstrap-admission-summary';d.className='disclosure';d.innerHTML='<summary>Bootstrap runtime</summary><div id="bootstrap-admission-body" class="bootstrap-mirror"></div>';admission.appendChild(d);}
 const sys=$('inspector-system');if(sys){const d=document.createElement('details');d.id='bootstrap-system-summary';d.className='disclosure';d.open=true;d.innerHTML='<summary>Bootstrap runtime</summary><div id="bootstrap-system-body" class="bootstrap-mirror"></div>';sys.prepend(d);}
 $('bootstrap-raw-toggle')?.addEventListener('click',loadBootstrapRaw);$('bootstrap-download')?.addEventListener('click',downloadBootstrapRaw);
}
function bootstrapStepMarkup(step){const st=String(step.status||'PENDING');const icon={PASS:'✓',FAIL:'!',START:'•',PROGRESS:'•',INFO:'•',PENDING:'○'}[st]||'○';const detail=step.detail?`<small>${bootstrapEsc(step.detail)}</small>`:'';const pc=(Number.isFinite(step.bytes)&&Number.isFinite(step.total_bytes)&&step.total_bytes>0)?`<span>${Math.min(100,Math.round(step.bytes/step.total_bytes*100))}%</span>`:'';return `<li class="bootstrap-step s-${st.toLowerCase()}"><i aria-hidden="true">${icon}</i><div><strong>${bootstrapEsc(step.label)}</strong>${detail}</div>${pc}<b>${bootstrapEsc(st)}</b></li>`;}
function compressedBootstrap(s){const n=s.summary||{},f=(s.steps||[]).find(x=>x.status==='FAIL');if(f)return `<strong>Bootstrap bloccato · ${bootstrapEsc(f.label)}</strong><p>${bootstrapEsc(f.detail||f.code||'Errore runtime')}</p>`;if(s.overall==='READY')return `<strong>Bootstrap completato · ${n.passed||0}/${n.total||0}</strong><p>Runtime locale verificato e pronto.</p>`;return `<strong>Bootstrap in corso · ${n.passed||0}/${n.total||0}</strong><p>Ogni passaggio viene registrato nel journal locale.</p>`;}
function renderBootstrap(status){ensureBootstrapSurface();if(!status||status.schema!==BOOTSTRAP_STATUS_SCHEMA)return;const steps=status.steps||[];if($('bootstrap-steps'))$('bootstrap-steps').innerHTML=steps.map(bootstrapStepMarkup).join('');text('bootstrap-title',status.overall==='READY'?'Bootstrap verificato':status.overall==='BLOCKED'?'Bootstrap bloccato':'Preparazione auditabile');const j=status.journal||{};text('bootstrap-integrity',j.integrity==='OK'?'journal ✓':'journal '+String(j.integrity||'unknown').toLowerCase());$('bootstrap-integrity')?.classList.toggle('blocked',j.integrity!=='OK');const failure=steps.find(x=>x.status==='FAIL')||status.fallback_failure,a=$('bootstrap-alert');if(a){if(failure){const r=failure.remediation||{};a.hidden=false;a.innerHTML=`<strong>${bootstrapEsc(failure.code||'BOOTSTRAP_FAILED')}</strong><p>${bootstrapEsc(failure.detail||'Il runtime locale non è pronto.')}</p>${r.label?`<p class="bootstrap-remediation">Azione: ${bootstrapEsc(r.label)}</p>`:''}`;}else{a.hidden=true;a.textContent='';}}const m=compressedBootstrap(status);if($('bootstrap-admission-body'))$('bootstrap-admission-body').innerHTML=m;if($('bootstrap-system-body'))$('bootstrap-system-body').innerHTML=m;}
async function bootstrapFetchRaw(){const h={};if(state.token)h.Authorization='Bearer '+state.token;const r=await fetch('/api/v5/bootstrap/raw',{headers:h,cache:'no-store'});if(!r.ok)throw new Error('raw diagnostic log unavailable');return r;}
async function loadBootstrapRaw(){try{const r=await bootstrapFetchRaw(),pre=$('bootstrap-raw');pre.textContent=await r.text()||'(journal vuoto)';pre.hidden=!pre.hidden;text('bootstrap-raw-toggle',pre.hidden?'Mostra log raw':'Nascondi log raw');}catch(e){const a=$('bootstrap-alert');if(a){a.hidden=false;a.textContent=e.message;}}}
async function downloadBootstrapRaw(){try{const r=await bootstrapFetchRaw(),blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ikant-bootstrap-events.jsonl';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}catch(e){const a=$('bootstrap-alert');if(a){a.hidden=false;a.textContent=e.message;}}}
const renderProductS9=renderProduct;renderProduct=function(out){renderProductS9(out);const s=out?.diagnostics?.bootstrap_observability;if(s)renderBootstrap(s);};ensureBootstrapSurface();if(state.product?.diagnostics?.bootstrap_observability)renderBootstrap(state.product.diagnostics.bootstrap_observability);
