'use strict';
const BOOTSTRAP_STATUS_SCHEMA='ikant-bootstrap-observability/v0.29-test';
function bootstrapEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function ensureBootstrapSurface(){if($('bootstrap-journey'))return;const setup=$('setup-panel')?.querySelector('.setup-main');if(!setup)return;const box=document.createElement('details');box.id='bootstrap-journey';box.className='disclosure';box.innerHTML='<summary>Passaggi</summary><ol id="bootstrap-steps" class="bootstrap-steps"></ol><div id="bootstrap-alert" class="bootstrap-alert" role="alert" hidden></div><div class="bootstrap-actions"><button id="bootstrap-raw-toggle" class="text-button" type="button">Log</button><button id="bootstrap-download" class="text-button" type="button">Salva log</button></div><pre id="bootstrap-raw" hidden></pre>';setup.appendChild(box);$('bootstrap-raw-toggle')?.addEventListener('click',loadBootstrapRaw);$('bootstrap-download')?.addEventListener('click',downloadBootstrapRaw);}
function renderBootstrap(status){ensureBootstrapSurface();if(status?.schema!==BOOTSTRAP_STATUS_SCHEMA)return;const steps=status.steps||[],host=$('bootstrap-steps');if(host)host.innerHTML=steps.map(s=>`<li><span>${s.status==='PASS'?'✓':s.status==='FAIL'?'!':'·'}</span><strong>${bootstrapEsc(s.label)}</strong>${s.detail?`<small>${bootstrapEsc(s.detail)}</small>`:''}</li>`).join('');const failure=steps.find(x=>x.status==='FAIL')||status.fallback_failure,a=$('bootstrap-alert');if(a){a.hidden=!failure;a.textContent=failure?bootstrapEsc(failure.detail||failure.code||'Preparazione bloccata'):'';}}
async function bootstrapFetchRaw(){const h={};if(state.token)h.Authorization='Bearer '+state.token;const r=await fetch('/api/v5/bootstrap/raw',{headers:h,cache:'no-store'});if(!r.ok)throw new Error('log non disponibile');return r;}
async function loadBootstrapRaw(){try{const r=await bootstrapFetchRaw(),pre=$('bootstrap-raw');pre.textContent=await r.text()||'(vuoto)';pre.hidden=!pre.hidden;}catch(e){text('setup-diagnostics',e.message);}}
async function downloadBootstrapRaw(){try{const r=await bootstrapFetchRaw(),blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ikant-runtime.jsonl';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}catch(e){text('setup-diagnostics',e.message);}}
const renderProductBase=renderProduct;renderProduct=function(out){renderProductBase(out);const s=out?.diagnostics?.bootstrap_observability;if(s)renderBootstrap(s);};ensureBootstrapSurface();if(state.product?.diagnostics?.bootstrap_observability)renderBootstrap(state.product.diagnostics.bootstrap_observability);
