'use strict';
const IKANT_PENDING_PRIMARY='iKant: [PENDING - la risposta validata non e ancora stata emessa]';
function primaryText(frame){const value=String(frame?.primary_text||'').trim();if(value)return value;const spoken=extractSurfaceA(frame);return spoken?('iKant: '+spoken):IKANT_PENDING_PRIMARY;}
function renderPrimaryFrame(frame){text('dashboard',primaryText(frame));const meta=document.querySelectorAll('.semantic-meta span');if(meta[0])meta[0].textContent='Surface A · chat primaria';if(meta[1])meta[1].textContent='HSPv2 · dettagli on demand';const detail=String(frame?.text||'');const transport={receipt:frame?.receipt||{},render_contract:frame?.render_contract||{},primary_text:frame?.primary_text||IKANT_PENDING_PRIMARY};text('frame-inspect',detail+'\n\n--- transport / projection ---\n'+JSON.stringify(transport,null,2));syncEmpty();}
buildWebAck=function(frame){const r=frame.receipt||{};const canonical=String(frame.text||'');return {schema:WEB_ACK_SCHEMA,runtime_session_id:r.runtime_session_id,epoch:r.epoch,frame_seq:r.frame_seq,frame_sha256:r.frame_sha256,visible_text:canonical,visible_text_sha256:r.frame_sha256,epistemic_authority:0.0,execution_authority:0.0};};
renderLegacyFrame=async function(frame){if(!frame||frame.schema!==WEB_FRAME_SCHEMA)throw new Error('unexpected activation frame');state.frame=frame;renderPrimaryFrame(frame);await apiRetry('/api/v1/frame/ack',{method:'POST',body:buildWebAck(frame)});};
extractSurfaceA=function(frame){const value=String(frame?.primary_text||'').trim();if(value.startsWith('iKant: ')){const out=value.slice('iKant: '.length).trim();return out.startsWith('[PENDING')?'':out;}return '';};
renderShellResponse=async function(response){if(!response||response.schema!==SHELL_SCHEMA)throw new Error('unexpected shell response');if(response.status==='RELEASED'&&response.frame===null){state.shell.next_seq=response.next_seq;state.shell.last_acked_frame=response.last_acked_frame||state.shell.last_acked_frame;shellStatus('released');released(true);return response;}const frame=response.frame;if(!frame||frame.schema!==WEB_FRAME_SCHEMA)throw new Error('shell response missing canonical frame');state.frame=frame;renderPrimaryFrame(frame);released(false);const op=response.operation||{};const ack={schema:SHELL_ACK_SCHEMA,shell_id:state.shell.shell_id,client_id:clientId,seq:op.seq,idempotency_key:op.idempotency_key,frame_ack:buildWebAck(frame)};const confirmed=await apiRetry('/api/v2/shell/ack',{method:'POST',body:ack});if(!confirmed||confirmed.schema!==SHELL_SCHEMA||confirmed.acknowledged!==true)throw new Error('exact ACK failed');state.shell.next_seq=confirmed.next_seq;state.shell.last_acked_frame=confirmed.last_acked_frame||null;if(confirmed.status==='RELEASED'){shellStatus('released');released(true);}else{shellStatus('ready');released(false);freezeActive(false);}maybeSpeak(frame);return confirmed;};
$('turn-form').addEventListener('submit',e=>{const value=$('intent').value;if(!value.trim())return;text('dashboard',IKANT_PENDING_PRIMARY);show('empty-state',false);shellStatus('busy');},true);
$('inspector-button').addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();$('active-panel').classList.contains('inspector-open')?closeInspector():openInspector('inspect');},true);
