'use strict';
(() => {
  const EPI_INDEX_SCHEMA='ikant-epistemic-index/v0.28-test',EPI_WORKSPACE_SCHEMA='ikant-epistemic-workspace/v0.28-test',LEGACY_LAYOUT_LABELS=['Graph','List'];
  const epi={index:null,cycle:null,layout:'graph',loading:false}; const el=id=>document.getElementById(id);
  function escapeHTML(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function bindingHeaders(){const f=state?.shell?.last_acked_frame;if(!state?.shell?.shell_id||!f)throw new Error('serve un frame confermato');return {'X-iKant-Shell-Id':state.shell.shell_id,'X-iKant-Client-Id':clientId,'X-iKant-Frame-Session':f.runtime_session_id,'X-iKant-Frame-Epoch':String(f.epoch),'X-iKant-Frame-Seq':String(f.frame_seq),'X-iKant-Frame-SHA256':f.frame_sha256};}
  async function epiApi(path){return api(path,{headers:bindingHeaders()});}
  function ensureUI(){const h=el('inspector-artifacts');if(!h||h.dataset.ready==='true')return;h.dataset.ready='true';h.innerHTML='<div class="epi-head"><strong id="epi-cycle-title">Tracce</strong><div><button id="epi-graph" class="epi-tab active" type="button">Rete</button><button id="epi-list" class="epi-tab" type="button">Elenco</button></div></div><div id="epi-summary" class="epi-summary" aria-live="polite"></div><select id="epi-history" class="epi-select" aria-label="Ciclo"></select><div id="epi-canvas" class="epi-canvas"></div><div id="epi-peek" class="epi-peek" hidden></div><div class="epi-actions"><button id="epi-json" class="secondary" type="button" hidden>JSON</button><button id="epi-docx" class="secondary" type="button" hidden>DOCX</button><button id="epi-refresh" class="text-button" type="button">Aggiorna</button></div><details class="disclosure"><summary>Integrità</summary><pre id="epi-integrity"></pre></details>';
    el('epi-graph').addEventListener('click',()=>setLayout('graph'));el('epi-list').addEventListener('click',()=>setLayout('list'));el('epi-history').addEventListener('change',e=>loadCycle(e.target.value));el('epi-refresh').addEventListener('click',()=>loadIndex(true));el('epi-json').addEventListener('click',()=>downloadArtifact('JSON'));el('epi-docx').addEventListener('click',()=>downloadArtifact('DOCX'));}
  function setLayout(x){epi.layout=x;el('epi-graph')?.classList.toggle('active',x==='graph');el('epi-list')?.classList.toggle('active',x==='list');renderCycle();}
  async function loadIndex(force=false){ensureUI();if(epi.loading&&!force)return;epi.loading=true;text('epi-summary','Aggiornamento…');try{const o=await epiApi('/api/v4/epistemic/index');if(o?.schema!==EPI_INDEX_SCHEMA)throw new Error('indice non valido');epi.index=o;const s=el('epi-history');s.replaceChildren();for(const row of o.cycles||[]){const op=document.createElement('option');op.value=row.cycle_id;op.textContent=(row.current?'● ':'')+row.cycle_id;s.appendChild(op);}const target=o.current_cycle_id||(o.cycles?.[0]?.cycle_id||'');if(target){s.value=target;await loadCycle(target);}else text('epi-summary','Nessuna traccia disponibile.');}catch(_){text('epi-summary','Tracce non disponibili per lo stato corrente.');}finally{epi.loading=false;}}
  async function loadCycle(c){if(!c)return;try{const o=await epiApi('/api/v4/epistemic/cycle?cycle_id='+encodeURIComponent(c));if(o?.schema!==EPI_WORKSPACE_SCHEMA)throw new Error('ciclo non valido');epi.cycle=o;renderCycle();}catch(_){text('epi-summary','Ciclo non disponibile.');}}
  function publicKind(k){return ({claim:'dato',observation:'osservazione',goal:'obiettivo',constraint:'vincolo',memory:'memoria',hypothesis:'ipotesi',action:'azione',prediction:'previsione',conflict:'conflitto',directive:'indicazione',downgrade:'revisione',backlog:'da verificare'})[String(k||'').toLowerCase()]||'oggetto';}
  function renderCycle(){const c=epi.cycle,canvas=el('epi-canvas');if(!c||!canvas)return;const s=c.summary||{};text('epi-cycle-title',c.current?'Tracce · attuale':'Tracce');text('epi-summary',`${(c.objects||[]).length} oggetti · ${s.epistemic_debt_open_count??0} da verificare`);text('epi-integrity',JSON.stringify({frame_binding:c.frame_binding,snapshot_sha256:c.snapshot_sha256,intent_sha256:c.intent_sha256,read_only:c.read_only},null,2));show('epi-json',!!c.artifacts?.json?.available);show('epi-docx',!!c.artifacts?.docx?.available);if(epi.layout==='list'){canvas.replaceChildren();for(const o of c.objects||[]){const b=document.createElement('button');b.className='epi-row';b.type='button';b.innerHTML=`<span>${escapeHTML(publicKind(o.kind))}</span><strong>${escapeHTML(o.label)}</strong>`;b.addEventListener('click',()=>peek(o));canvas.appendChild(b);}}else{canvas.replaceChildren();const st=document.createElement('div');st.className='epi-orbit-stage';for(const [i,n] of (c.graph?.nodes||[]).entries()){const b=document.createElement('button');b.type='button';b.className='epi-node';b.textContent='R'+i;b.title='Livello '+(i+1);b.setAttribute('aria-label','Livello '+(i+1));b.addEventListener('click',()=>peek({kind:'livello',label:'Livello '+(i+1),source:'runtime'}));st.appendChild(b);}canvas.appendChild(st);}}
  function peek(o){const p=el('epi-peek');if(!p)return;p.hidden=false;p.innerHTML=`<button type="button" aria-label="Chiudi">×</button><strong>${escapeHTML(o.label||'')}</strong><small>${escapeHTML(publicKind(o.kind))}</small>`;p.querySelector('button').onclick=()=>p.hidden=true;}
  async function downloadArtifact(kind){const cycle=epi.cycle?.cycle_id;if(!cycle)return;const headers={...bindingHeaders()};if(state.token)headers.Authorization='Bearer '+state.token;const r=await fetch(`/api/v4/epistemic/artifact?cycle_id=${encodeURIComponent(cycle)}&kind=${encodeURIComponent(kind)}`,{headers,cache:'no-store'});if(!r.ok)return;text('epi-summary','File pronto.');const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=kind==='DOCX'?`Trace_${cycle}.docx`:`Trace_${cycle}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  document.addEventListener('keydown',event=>{if(event.code==='Space'&&state?.view==='artifacts'&&epi.cycle){const active=document.activeElement?.closest?.('.epi-row,.epi-node');if(active){event.preventDefault();active.click();}}});
  window.ikantTrace={loadIndex};ensureUI();
})();
