'use strict';
(()=>{
const $=id=>document.getElementById(id);
let revision=0,dirty=false,timer=null;
function token(){return sessionStorage.getItem('ikantBearer')||'';}
function setVoiceAvailable(on){if($('voice-button'))$('voice-button').hidden=!on;const cmd=document.querySelector('[data-command="voice"]');if(cmd)cmd.hidden=!on;}
async function request(path,{method='GET',body=null}={}){const h={Accept:'application/json'};if(token())h.Authorization='Bearer '+token();if(body!==null)h['Content-Type']='application/json';const r=await fetch(path,{method,headers:h,body:body===null?undefined:JSON.stringify(body),cache:'no-store'});const raw=await r.text();let out={};if(raw){try{out=JSON.parse(raw);}catch(_){out={error:raw};}}if(!r.ok)throw new Error(String(out.message||out.error||('HTTP '+r.status)).slice(0,240));return out;}
function clear(host){while(host?.firstChild)host.firstChild.remove();}
function serviceRow(label,evidence){const row=document.createElement('div');row.className='foundation-service';const strong=document.createElement('strong');strong.textContent=label;const small=document.createElement('small');small.textContent=evidence;row.append(strong,small);return row;}
function renderServices(catalog){const host=$('foundation-services');if(!host)return;clear(host);const rows=Array.isArray(catalog?.services)?catalog.services:[];const ids=new Set(rows.map(s=>String(s.id||'')));for(const s of rows)host.appendChild(serviceRow(String(s.label||s.id||'Servizio'),String(s.evidence||'')));const traces=document.querySelector('[data-inspector-view="artifacts"]');if(traces)traces.hidden=!(ids.has('epistemic_inspection')||ids.has('json_snapshot')||ids.has('docx_artifact'));setVoiceAvailable(ids.has('loopback_voice'));clientServices(host);if(!host.childElementCount){const p=document.createElement('p');p.className='foundation-muted';p.textContent='Nessun servizio dimostrabile in questo stato.';host.appendChild(p);}}
async function clientServices(host){try{const SR=window.SpeechRecognition;if(SR&&typeof SR.available==='function'){const lang=navigator.language||'it-IT';const a=await SR.available({langs:[lang],processLocally:true});if(a==='available'){host.appendChild(serviceRow('Voce sul dispositivo','SpeechRecognition attestata processLocally'));setVoiceAvailable(true);}}}catch(_){/* local capability absent */}const voices=('speechSynthesis'in window)?speechSynthesis.getVoices().filter(v=>v.localService===true):[];if(voices.length)host.appendChild(serviceRow('Audio locale','Voce browser localService disponibile'));}
function renderEpistemic(v){const host=$('foundation-epistemic');if(!host)return;clear(host);const title=document.createElement('strong');title.textContent=String(v?.label||'Nessun ciclo cognitivo disponibile');const grid=document.createElement('dl');grid.className='foundation-metrics';for(const [label,value] of [['Supporti diretti',v?.direct_support??0],['Derivazioni',v?.derived_items??0],['Conflitti aperti',v?.open_conflicts??0],['Elementi incerti',v?.uncertain_items??0]]){const dt=document.createElement('dt');dt.textContent=label;const dd=document.createElement('dd');dd.textContent=String(value);grid.append(dt,dd);}const note=document.createElement('p');note.className='foundation-muted';note.textContent=String(v?.meaning||'Provenienza e conflitti; non certificazione del vero.');host.append(title,grid,note);}
function renderConfig(c){revision=Number(c?.revision||0);if(dirty)return;const guard=c?.guardrails||{};if($('foundation-meta'))$('foundation-meta').value=String(c?.meta_prompt||'');if($('foundation-evidence'))$('foundation-evidence').value=String(guard.evidence_mode||'baseline');if($('foundation-conflict'))$('foundation-conflict').value=String(guard.conflict_mode||'surface');if($('foundation-interpretive'))$('foundation-interpretive').value=String(guard.interpretive_hypotheses||'bounded');if($('foundation-words'))$('foundation-words').value=String(guard.max_reply_words||160);}
async function refresh(){if(!token()||$('active-panel')?.hidden)return;try{const out=await request('/api/v7/foundation');if(out?.schema!=='ikant-foundation/v1-test')return;renderServices(out.capabilities);renderEpistemic(out.epistemic_value);renderConfig(out.config);if($('foundation-version'))$('foundation-version').textContent=String(out.foundation_version||'1.0-test');}catch(e){if($('foundation-save-status'))$('foundation-save-status').textContent=String(e.message||'').slice(0,160);}}
async function save(){const body={expected_revision:revision,meta_prompt:$('foundation-meta')?.value||'',guardrails:{evidence_mode:$('foundation-evidence')?.value||'baseline',conflict_mode:$('foundation-conflict')?.value||'surface',interpretive_hypotheses:$('foundation-interpretive')?.value||'bounded',max_reply_words:Number($('foundation-words')?.value||160)}};const b=$('foundation-save');if(b)b.disabled=true;try{const out=await request('/api/v7/config',{method:'POST',body});revision=Number(out.revision||revision+1);dirty=false;if($('foundation-save-status'))$('foundation-save-status').textContent='Salvato';await refresh();}catch(e){if($('foundation-save-status'))$('foundation-save-status').textContent=String(e.message||'Configurazione non salvata').slice(0,160);}finally{if(b)b.disabled=false;}}
for(const id of ['foundation-meta','foundation-evidence','foundation-conflict','foundation-interpretive','foundation-words'])$(id)?.addEventListener('input',()=>{dirty=true;if($('foundation-save-status'))$('foundation-save-status').textContent='Modifiche non salvate';});$('foundation-save')?.addEventListener('click',save);
const active=$('active-panel');if(active)new MutationObserver(()=>{if(!active.hidden)refresh();}).observe(active,{attributes:true,attributeFilter:['hidden']});$('status-button')?.addEventListener('click',()=>setTimeout(refresh,0));document.querySelector('[data-inspector-view="system"]')?.addEventListener('click',()=>setTimeout(refresh,0));document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});timer=setInterval(()=>{if(!$('active-panel')?.hidden)refresh();},5000);window.addEventListener('beforeunload',()=>clearInterval(timer));
})();
