'use strict';
(()=>{
const ENDPOINT='/api/v9/work/current',INTERVAL=280,GRACE=2500;let timer=null,inflight=false,polling=false,saw=false,epoch=0,started=0,last='';
function ensure(){let e=document.getElementById('work-bubble');if(e)return e;const host=document.getElementById('semantic-window');if(!host)return null;e=document.createElement('section');e.id='work-bubble';e.className='work-bubble';e.hidden=true;e.setAttribute('role','status');e.setAttribute('aria-live','polite');const row=document.createElement('div');row.className='work-bubble-row';const pulse=document.createElement('span');pulse.className='work-bubble-pulse';pulse.setAttribute('aria-hidden','true');const copy=document.createElement('span');copy.id='work-bubble-copy';copy.className='work-bubble-copy';const d=document.createElement('details');d.className='work-bubble-details';const s=document.createElement('summary');s.textContent='Dettagli';const more=document.createElement('span');more.id='work-bubble-detail';more.className='work-bubble-detail';d.append(s,more);row.append(pulse,copy,d);e.append(row);host.insertBefore(e,document.getElementById('dashboard')||host.firstChild);return e;}
function mode(){let floating=false;try{floating=new URLSearchParams(location.search).get('shell')==='floating'||matchMedia('(display-mode: standalone)').matches;}catch(_){}document.documentElement.dataset.ikantShellMode=floating?'floating':'web';}
function hide(){const e=ensure();if(e){e.hidden=true;e.removeAttribute('aria-busy');}last='';}
function render(o){const e=ensure();if(!e)return;if(!o?.active){if(saw)stop();return;}saw=true;e.hidden=false;e.dataset.moment=String(o.moment||'');e.setAttribute('aria-busy','true');const msg=String(o.message||'Sto lavorando.').slice(0,180),detail=String(o.detail||'').slice(0,220);const copy=document.getElementById('work-bubble-copy'),more=document.getElementById('work-bubble-detail');if(copy&&(last!==o.phase||copy.textContent!==msg))copy.textContent=msg;if(more){const f=o.facts||{},bits=[];if(Number.isInteger(f.unit_count)&&f.unit_count>1)bits.push(`${f.unit_count} parti`);if(f.route)bits.push(String(f.route).replaceAll('_',' ').toLowerCase());more.textContent=[detail,...bits.slice(0,2)].filter(Boolean).join(' · ');}last=String(o.phase||'');}
async function poll(local){if(!inflight||polling||local!==epoch)return;polling=true;try{const out=await api(ENDPOINT);if(!inflight||local!==epoch)return;if(out?.schema!=='ikant-reactive-work-state/v1-test')return;if(!out.active&&!saw){if(performance.now()-started<GRACE)return;stop();return;}render(out);}catch(_){}finally{polling=false;}}
function start(){stop();inflight=true;saw=false;started=performance.now();const local=++epoch;poll(local);timer=setInterval(()=>poll(local),INTERVAL);}
function stop(){inflight=false;saw=false;epoch++;if(timer){clearInterval(timer);timer=null;}hide();}
function bind(){ensure();mode();const form=document.getElementById('turn-form');if(form&&!form.dataset.reactiveBound){form.dataset.reactiveBound='true';form.addEventListener('submit',start,{capture:true});}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();window.ikantWork={start,stop};
})();
