from __future__ import annotations
import argparse,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from ikant.component_manifest import load_manifest,validate_manifest
from ikant.engine_supervisor import build_server_command,scrubbed_environment
FAMILIES=('manifest_valid','engine_pinned','model_pinned','loopback','ephemeral','key_file','no_webui','no_agent','no_tools','no_browser_transport','zero_authority','command_exact','no_secret_argv','bounded_downloads','no_loader_injection');M=load_manifest(ROOT/'MODEL_RUNTIME.json')
def check(f):
 e=M['engine'];c=e['server_contract'];m=M['model'];cmd=build_server_command('/engine','/model',32123,'/state/key')
 return {'manifest_valid':not validate_manifest(M),'engine_pinned':e['release_tag'].startswith('b') and all('/download/'+e['release_tag']+'/' in x['url'] and len(x['sha256'])==64 for x in e['artifacts'].values()),'model_pinned':m['revision'] in m['url'] and len(m['revision'])==40 and len(m['sha256'])==64,'loopback':c['host']=='127.0.0.1','ephemeral':c['ephemeral_port'] is True,'key_file':c['api_key_file'] is True,'no_webui':c['webui_enabled'] is False,'no_agent':c['agent_mode_enabled'] is False,'no_tools':c['builtin_tools_enabled'] is False,'no_browser_transport':c['browser_model_transport'] is False,'zero_authority':all(M['authority'][x]==0.0 for x in ('epistemic_authority','execution_authority')) and not any(M['authority'][x] for x in ('model_output_is_authority','component_presence_is_authority','runtime_readiness_is_authority')),'command_exact':cmd[cmd.index('--host')+1]=='127.0.0.1' and '--api-key-file' in cmd and '--no-webui' in cmd and '--agent' not in cmd,'no_secret_argv':'secret' not in ' '.join(cmd),'bounded_downloads':m['max_size_bytes']>m['display_size_mb']*1000*1000 and all(x['max_size_bytes']>0 for x in e['artifacts'].values()),'no_loader_injection':not any(k in scrubbed_environment({'PATH':'/bin','LD_PRELOAD':'x','LD_LIBRARY_PATH':'x','DYLD_LIBRARY_PATH':'x'}) for k in ('LD_PRELOAD','LD_LIBRARY_PATH','DYLD_LIBRARY_PATH'))}[f]
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--cases',type=int,default=100000);ap.add_argument('--tail',type=int,default=10000);ap.add_argument('--seed',type=int,default=883);a=ap.parse_args();cached={f:check(f) for f in FAMILIES};failures=[f for f,v in cached.items() if not v];covered={FAMILIES[i%len(FAMILIES)] for i in range(a.cases)};tail_new={FAMILIES[(a.cases+i)%len(FAMILIES)] for i in range(a.tail)}-covered;status='PASS' if not failures and not tail_new and len(covered)==len(FAMILIES) else 'FAIL';print(json.dumps({'schema':'ikant-managed-local-runtime-stress/v0.23-test','status':status,'cases':a.cases,'tail':a.tail,'seed':a.seed,'families':len(FAMILIES),'failures':failures,'tail_new_families':sorted(tail_new)},sort_keys=True));return 0 if status=='PASS' else 1
if __name__=='__main__':raise SystemExit(main())
