import fs from 'node:fs';
import http from 'node:http';
import {spawn,spawnSync} from 'node:child_process';

const sourcePath=process.argv[2]||'ikant/web/public-v1.js';
const timeoutMs=2500;
function findBrowser(){if(process.env.IKANT_BROWSER)return process.env.IKANT_BROWSER;for(const name of ['google-chrome','chromium','chromium-browser']){const r=spawnSync('sh',['-c',`command -v ${name}`],{encoding:'utf8'});if(r.status===0&&r.stdout.trim())return r.stdout.trim();}throw new Error('Chromium-compatible browser not found');}
function getJson(url){return new Promise((resolve,reject)=>{const req=http.get(url,res=>{let data='';res.setEncoding('utf8');res.on('data',d=>data+=d);res.on('end',()=>{try{resolve(JSON.parse(data));}catch(e){reject(e);}});});req.on('error',reject);req.setTimeout(300,()=>req.destroy(new Error('timeout')));});}
async function waitJson(url,deadline=Date.now()+5000){while(Date.now()<deadline){try{return await getJson(url);}catch{}await new Promise(r=>setTimeout(r,80));}throw new Error('DevTools endpoint unavailable');}
function extractFunction(src,name){const needle=`function ${name}(`,start=src.indexOf(needle);if(start<0)throw new Error(`missing ${name}`);const brace=src.indexOf('{',start);let depth=0,quote='',escape=false;for(let i=brace;i<src.length;i++){const c=src[i];if(quote){if(escape){escape=false;continue;}if(c==='\\'){escape=true;continue;}if(c===quote)quote='';continue;}if(c==='"'||c==="'"||c==='`'){quote=c;continue;}if(c==='{')depth++;else if(c==='}'){depth--;if(depth===0)return src.slice(start,i+1);}}throw new Error(`unterminated ${name}`);}
class CDP{constructor(ws){this.ws=ws;this.id=0;this.pending=new Map();ws.onmessage=e=>{const msg=JSON.parse(e.data);if(msg.id&&this.pending.has(msg.id)){const p=this.pending.get(msg.id);clearTimeout(p.timer);this.pending.delete(msg.id);msg.error?p.reject(new Error(msg.error.message)):p.resolve(msg.result);}};}call(method,params={},ms=timeoutMs){return new Promise((resolve,reject)=>{const id=++this.id,timer=setTimeout(()=>{this.pending.delete(id);reject(new Error(`${method} timeout`));},ms);this.pending.set(id,{resolve,reject,timer});this.ws.send(JSON.stringify({id,method,params}));});}}
const src=fs.readFileSync(sourcePath,'utf8');const funcs=['setHidden','keepAcceptanceWritable','syncAdmission','installAdmissionRepair'].filter(n=>src.includes(`function ${n}(`)).map(n=>extractFunction(src,n)).join('\n');const browser=findBrowser(),port=9300+(process.pid%500),profile=`/tmp/ikant-browser-liveness-${process.pid}`;const child=spawn(browser,['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-first-run',`--user-data-dir=${profile}`,`--remote-debugging-port=${port}`,'--remote-allow-origins=*','about:blank'],{stdio:'ignore'});let ws;
try{const targets=await waitJson(`http://127.0.0.1:${port}/json/list`),target=targets.find(x=>x.type==='page')||targets[0];ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('websocket open timeout')),2000);ws.onopen=()=>{clearTimeout(t);resolve();};ws.onerror=()=>{clearTimeout(t);reject(new Error('websocket error'));};});const cdp=new CDP(ws);const setup=`document.body.innerHTML=\`<section id="pair-panel"><form id="pair-form"><input id="pair-code"></form><p id="pair-error"></p></section><section id="admission-panel" hidden><span id="step-accept"></span><span id="step-probe"></span><form id="accept-form"><input id="accept-text"><button type="submit">Accetta</button></form><button id="probe-button">Probe</button><button id="init-button">Init</button><p id="admission-copy"></p></section>\`;const $=id=>document.getElementById(id);${funcs};installAdmissionRepair();setTimeout(()=>document.body.dataset.ikantTick='1',0);'installed'`;await cdp.call('Runtime.evaluate',{expression:setup,returnByValue:true});await new Promise(r=>setTimeout(r,30));const tick=await cdp.call('Runtime.evaluate',{expression:'document.body.dataset.ikantTick||""',returnByValue:true});await cdp.call('Runtime.evaluate',{expression:'document.getElementById("pair-code").focus();document.getElementById("pair-code").value="";true',returnByValue:true});await cdp.call('Input.insertText',{text:'ikant-liveness'});const typed=await cdp.call('Runtime.evaluate',{expression:'document.getElementById("pair-code").value',returnByValue:true});await cdp.call('Runtime.evaluate',{expression:'document.getElementById("step-accept").classList.add("done");true',returnByValue:true});await new Promise(r=>setTimeout(r,30));const admission=await cdp.call('Runtime.evaluate',{expression:'({acceptHidden:document.querySelector("#accept-form button").hidden,probeHidden:document.getElementById("probe-button").hidden,initHidden:document.getElementById("init-button").hidden,copy:document.getElementById("admission-copy").textContent})',returnByValue:true});const ok=tick.result.value==='1'&&typed.result.value==='ikant-liveness'&&admission.result.value.acceptHidden===true&&admission.result.value.probeHidden===false;const result={schema:'ikant-public-browser-liveness/v1-test',status:ok?'PASS':'FAIL',event_loop_tick:tick.result.value,input_value:typed.result.value,admission:admission.result.value,source:sourcePath,real_browser_execution:true};console.log(JSON.stringify(result));if(!ok)process.exitCode=1;}finally{try{ws?.close();}catch{}child.kill('SIGKILL');}