import fs from 'node:fs';
import {spawn,spawnSync} from 'node:child_process';

const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const timeoutMs=Number(process.env.IKANT_S17BIS_BROWSER_TIMEOUT_MS||15000);
function findBrowser(){if(process.env.IKANT_BROWSER)return process.env.IKANT_BROWSER;for(const n of ['google-chrome','chromium','chromium-browser']){const r=spawnSync('sh',['-c',`command -v ${n}`],{encoding:'utf8'});if(r.status===0&&r.stdout.trim())return r.stdout.trim();}throw new Error('Chromium-compatible browser not found');}
async function waitPort(profile,deadline=Date.now()+timeoutMs){const p=`${profile}/DevToolsActivePort`;while(Date.now()<deadline){try{const lines=fs.readFileSync(p,'utf8').trim().split(/\r?\n/),port=Number(lines[0]);if(port>0)return port;}catch{}await sleep(50);}throw new Error('DevToolsActivePort unavailable');}
async function waitJson(url,deadline=Date.now()+timeoutMs){let last='';while(Date.now()<deadline){try{const r=await fetch(url);if(r.ok)return r.json();last=`HTTP ${r.status}`;}catch(e){last=String(e?.message||e);}await sleep(70);}throw new Error(`DevTools endpoint unavailable: ${last}`);}
class CDP{constructor(ws){this.ws=ws;this.id=0;this.pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&this.pending.has(m.id)){const p=this.pending.get(m.id);clearTimeout(p.t);this.pending.delete(m.id);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result);}};}call(method,params={}){return new Promise((resolve,reject)=>{const id=++this.id,t=setTimeout(()=>{this.pending.delete(id);reject(new Error(`${method} timeout`));},timeoutMs);this.pending.set(id,{resolve,reject,t});this.ws.send(JSON.stringify({id,method,params}));});}}
async function evalv(cdp,expression,{awaitPromise=false}={}){const out=await cdp.call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise});if(out.exceptionDetails)throw new Error(out.exceptionDetails.text||'Runtime.evaluate exception');return out.result.value;}
async function waitValue(cdp,expression,predicate,label,deadline=Date.now()+timeoutMs){let last=null;while(Date.now()<deadline){try{last=await evalv(cdp,expression,{awaitPromise:true});if(predicate(last))return last;}catch(e){last={error:String(e?.message||e)};}await sleep(40);}throw new Error(`${label} condition timeout; last=${JSON.stringify(last)}`);}
async function startFixture(scenario){const child=spawn(process.env.PYTHON||'python',['scripts/runtime_recovery_browser_fixture.py','--scenario',scenario],{stdio:['ignore','pipe','pipe']});let stderr='',buf='';child.stderr.on('data',d=>stderr=(stderr+d.toString('utf8')).slice(-4096));const line=await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error(`fixture startup timeout ${scenario}: ${stderr}`)),10000);child.stdout.on('data',d=>{buf+=d.toString('utf8');const i=buf.indexOf('\n');if(i>=0){clearTimeout(t);resolve(buf.slice(0,i));}});child.on('exit',c=>{clearTimeout(t);reject(new Error(`fixture exited ${c}: ${stderr}`));});});return {child,info:JSON.parse(line),stderr:()=>stderr};}
function webAck(frame){const r=frame.receipt||{};return {schema:'ikant-web-human-ack/v0.20-test',runtime_session_id:r.runtime_session_id,epoch:r.epoch,frame_seq:r.frame_seq,frame_sha256:r.frame_sha256,visible_text:String(frame.text||''),visible_text_sha256:r.frame_sha256,epistemic_authority:0.0,execution_authority:0.0};}
const requiredDomIds=['pair-panel','pair-form','active-panel','turn-form','intent','send-button','status-button','inspector','foundation-config-disclosure','foundation-save','released-panel','resume-button','command-palette'];

async function scenarioRun(scenario){
  const fixture=await startFixture(scenario),origin=`http://127.0.0.1:${fixture.info.port}`,browser=findBrowser(),profile=`/tmp/ikant-s17bis-${scenario}-${process.pid}-${Date.now()}`;
  const b=spawn(browser,['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-first-run',`--user-data-dir=${profile}`,'--remote-debugging-port=0','--remote-allow-origins=*','about:blank'],{stdio:['ignore','ignore','pipe']});let berr='',ws;b.stderr?.on('data',d=>berr=(berr+d.toString('utf8')).slice(-4096));
  try{
    const port=await waitPort(profile),targets=await waitJson(`http://127.0.0.1:${port}/json/list`),target=targets.find(x=>x.type==='page')||targets[0];if(!target?.webSocketDebuggerUrl)throw new Error('DevTools page target unavailable');ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('websocket open timeout')),5000);ws.onopen=()=>{clearTimeout(t);resolve();};ws.onerror=()=>{clearTimeout(t);reject(new Error('websocket error'));};});const cdp=new CDP(ws);await cdp.call('Page.enable');await cdp.call('Runtime.enable');await cdp.call('Page.navigate',{url:origin+'/'});
    await waitValue(cdp,`({origin:location.origin,ready:document.readyState,surface:typeof window.ikantSurfaceContract==='object',semanticWindow:!!document.getElementById('semantic-window')})`,v=>v?.origin===origin&&v?.ready==='complete'&&v?.surface===true&&v?.semanticWindow===true,'page and Surface Contract readiness');
    const census=await evalv(cdp,`({ids:${JSON.stringify(requiredDomIds)}.filter(id=>document.getElementById(id)).sort(),missing:${JSON.stringify(requiredDomIds)}.filter(id=>!document.getElementById(id)),buttons:document.querySelectorAll('button').length,forms:document.querySelectorAll('form').length,semanticWindow:!!document.getElementById('semantic-window'),surfaceContractScript:typeof window.ikantSurfaceContract==='object'})`);
    if(census.missing.length||!census.semanticWindow||!census.surfaceContractScript||census.buttons<15||census.forms<2)throw new Error(`DOM census failed: ${JSON.stringify(census)}`);
    const pair=await evalv(cdp,`(async()=>{const r=await fetch('/api/v1/pair',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({code:${JSON.stringify(fixture.info.pairing_code)}})});return {status:r.status,body:await r.json()};})()`,{awaitPromise:true});if(pair.status!==200||!pair.body?.bearer_token)throw new Error(`pair failed ${JSON.stringify(pair)}`);const auth=JSON.stringify('Bearer '+pair.body.bearer_token),client=`client-${scenario}-0000000000000001`;
    const opened=await evalv(cdp,`(async()=>{const r=await fetch('/api/v2/shell/open',{method:'POST',headers:{Authorization:${auth},'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({client_id:${JSON.stringify(client)}})});return {status:r.status,body:await r.json()};})()`,{awaitPromise:true});if(opened.status!==200||!opened.body?.shell_id)throw new Error(`open failed ${JSON.stringify(opened)}`);const o=opened.body,idem=`op-${scenario}-0000000000000001`;
    const command={schema:'ikant-advanced-web-shell-command/v0.26-test',shell_id:o.shell_id,client_id:client,seq:o.next_seq,op:'SYNC',idempotency_key:idem,expected_frame:o.last_acked_frame||null,payload:{}};
    const synced=await evalv(cdp,`(async()=>{const r=await fetch('/api/v2/shell/command',{method:'POST',headers:{Authorization:${auth},'Content-Type':'application/json',Accept:'application/json'},body:${JSON.stringify(JSON.stringify(command))}});return {status:r.status,body:await r.json()};})()`,{awaitPromise:true});if(synced.status!==200||synced.body?.status!=='FRAME_PENDING'||!synced.body?.frame)throw new Error(`SYNC failed ${JSON.stringify(synced)}`);const frame=synced.body.frame;
    if(fixture.info.expected_frame_sha256&&frame.receipt?.frame_sha256!==fixture.info.expected_frame_sha256)throw new Error('sealed frame digest changed after restart');
    if(fixture.info.expected_primary&&scenario==='surface'&&frame.primary_text!==fixture.info.expected_primary)throw new Error(`surface primary changed ${frame.primary_text}`);
    if(fixture.info.expected_primary&&scenario==='interrupted'&&!String(frame.primary_text||'').includes(fixture.info.expected_primary))throw new Error(`interrupted recovery message drift ${frame.primary_text}`);
    if(['interrupted','surface'].includes(scenario)&&frame.receipt?.kind!=='RECOVERY')throw new Error('recovery scenario did not seal RECOVERY frame');
    const ack={schema:'ikant-advanced-web-shell-ack/v0.26-test',shell_id:o.shell_id,client_id:client,seq:synced.body.operation.seq,idempotency_key:idem,frame_ack:webAck(frame)};
    const acked=await evalv(cdp,`(async()=>{const r=await fetch('/api/v2/shell/ack',{method:'POST',headers:{Authorization:${auth},'Content-Type':'application/json',Accept:'application/json'},body:${JSON.stringify(JSON.stringify(ack))}});return {status:r.status,body:await r.json()};})()`,{awaitPromise:true});if(acked.status!==200||acked.body?.acknowledged!==true)throw new Error(`ACK failed ${JSON.stringify(acked)}`);
    const state=await evalv(cdp,`(async()=>{const r=await fetch('/api/v1/state',{headers:{Authorization:${auth},Accept:'application/json'},cache:'no-store'});return {status:r.status,body:await r.json()};})()`,{awaitPromise:true});if(state.status!==200||state.body?.surface_phase!=='ACTIVE_CANONICAL')throw new Error(`lifecycle did not converge ${JSON.stringify(state)}`);
    return {scenario,frame_sha256:frame.receipt.frame_sha256,kind:frame.receipt.kind,dom_census:census,post_ack_surface_phase:state.body.surface_phase};
  }catch(e){throw new Error(`${scenario}: ${String(e?.message||e)}; browser=${berr}; fixture=${fixture.stderr()}`);}finally{try{ws?.close();}catch{}b.kill('SIGKILL');fixture.child.kill('SIGKILL');try{fs.rmSync(profile,{recursive:true,force:true});}catch{}}
}

const results=[];for(const s of ['sealed','interrupted','surface'])results.push(await scenarioRun(s));console.log(JSON.stringify({schema:'ikant-runtime-recovery-browser-liveness/v1-test',status:'PASS',real_chromium:true,production_reactive_http:true,real_dom_census:true,scenarios:results,epistemic_authority:0.0,execution_authority:0.0}));
