import fs from 'node:fs';
import {spawn,spawnSync} from 'node:child_process';

const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function browserPath(){if(process.env.IKANT_BROWSER)return process.env.IKANT_BROWSER;for(const n of ['google-chrome','chromium','chromium-browser']){const r=spawnSync('sh',['-c',`command -v ${n}`],{encoding:'utf8'});if(r.status===0&&r.stdout.trim())return r.stdout.trim();}throw new Error('Chromium-compatible browser not found');}
async function waitPort(profile,deadline=Date.now()+30000){const p=`${profile}/DevToolsActivePort`;while(Date.now()<deadline){try{const port=Number(fs.readFileSync(p,'utf8').split(/\r?\n/)[0]);if(port>0)return port;}catch{}await sleep(50);}throw new Error('DevToolsActivePort unavailable');}
async function waitJson(url,deadline=Date.now()+30000){let last='';while(Date.now()<deadline){try{const r=await fetch(url);if(r.ok)return r.json();last=`HTTP ${r.status}`;}catch(e){last=String(e?.message||e);}await sleep(80);}throw new Error('DevTools endpoint unavailable: '+last);}
class CDP{constructor(ws){this.ws=ws;this.id=0;this.pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&this.pending.has(m.id)){const p=this.pending.get(m.id);clearTimeout(p.timer);this.pending.delete(m.id);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result);}};}call(method,params={},ms=12000){return new Promise((resolve,reject)=>{const id=++this.id,timer=setTimeout(()=>{this.pending.delete(id);reject(new Error(method+' timeout'));},ms);this.pending.set(id,{resolve,reject,timer});this.ws.send(JSON.stringify({id,method,params}));});}}
async function evalv(cdp,expression,awaitPromise=false){const out=await cdp.call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise});if(out.exceptionDetails)throw new Error(out.exceptionDetails.text||'Runtime.evaluate exception');return out.result.value;}
async function waitValue(cdp,expression,predicate,label,deadline=Date.now()+10000){let last;while(Date.now()<deadline){last=await evalv(cdp,expression,true);if(predicate(last))return last;await sleep(50);}throw new Error(`${label} timeout: ${JSON.stringify(last)}`);}
async function fixture(){const child=spawn(process.env.PYTHON||'python',['scripts/runtime_epoch_browser_fixture.py'],{stdio:['ignore','pipe','pipe']});let err='';child.stderr.on('data',d=>{err=(err+d.toString()).slice(-4096);});const line=await new Promise((resolve,reject)=>{let b='';const t=setTimeout(()=>reject(new Error('fixture timeout: '+err)),10000);child.stdout.on('data',d=>{b+=d.toString();const i=b.indexOf('\n');if(i>=0){clearTimeout(t);resolve(b.slice(0,i));}});child.on('exit',c=>{clearTimeout(t);reject(new Error(`fixture exit ${c}: ${err}`));});});return {child,info:JSON.parse(line),err:()=>err};}

export async function runRuntimeEpochBrowserLiveness(){
 const fx=await fixture(),origin=`http://127.0.0.1:${fx.info.port}`,browser=browserPath(),profile=`/tmp/ikant-s17-browser-${process.pid}-${Date.now()}`;const chrome=spawn(browser,['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-first-run',`--user-data-dir=${profile}`,'--remote-debugging-port=0','--remote-allow-origins=*','about:blank'],{stdio:['ignore','ignore','pipe']});let berr='',ws;
 chrome.stderr?.on('data',d=>{berr=(berr+d.toString()).slice(-4096);});
 try{
  const port=await waitPort(profile),targets=await waitJson(`http://127.0.0.1:${port}/json/list`),target=targets.find(x=>x.type==='page')||targets[0];if(!target?.webSocketDebuggerUrl)throw new Error('DevTools page unavailable');ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('websocket timeout')),5000);ws.onopen=()=>{clearTimeout(t);resolve();};ws.onerror=()=>{clearTimeout(t);reject(new Error('websocket error'));};});const cdp=new CDP(ws);await cdp.call('Page.enable');await cdp.call('Runtime.enable');await cdp.call('Page.navigate',{url:origin+'/manifest.webmanifest'});await waitValue(cdp,'location.origin',v=>v===origin,'origin');
  const pair=await evalv(cdp,`(async()=>{const r=await fetch('/api/v1/pair',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({code:${JSON.stringify(fx.info.pairing_code)}})});return {status:r.status,body:await r.json()};})()`,true);if(pair?.status!==200||!pair?.body?.bearer_token)throw new Error('pair failed');const token=String(pair.body.bearer_token);
  await evalv(cdp,`(()=>{document.body.innerHTML='<main id="inspector-overview"></main><section id="active-panel"></section><span id="shell-status"></span><div id="conversation-log"></div>';sessionStorage.setItem('ikantBearer',${JSON.stringify(token)});return true;})()`);
  const surfaceSource=fs.readFileSync('ikant/web/surface-contract.js','utf8'),enduserSource=fs.readFileSync('ikant/web/enduser.js','utf8');await evalv(cdp,surfaceSource);await evalv(cdp,enduserSource);
  const first=await waitValue(cdp,`(()=>({label:document.getElementById('enduser-identity-label')?.textContent||'',facts:document.getElementById('enduser-identity-fingerprint')?.textContent||'',contract:document.documentElement.dataset.ikantSurfaceContract||''}))()`,v=>v?.label==='iKant locale'&&v?.facts.includes('epoca 1')&&v?.facts.includes('model-a')&&v?.contract==='bound','initial epoch UI');
  fs.copyFileSync(fx.info.model_next,fx.info.model_current);
  const secondSnapshot=await evalv(cdp,`(async()=>{window.ikantSurfaceContract.invalidate();const s=await window.ikantSurfaceContract.refresh(true);return {id:s?.runtime_epoch?.epoch_id,ordinal:s?.runtime_epoch?.ordinal,model:s?.runtime_epoch?.component?.model?.id};})()`,true);if(secondSnapshot?.ordinal!==2||secondSnapshot?.model!=='model-b')throw new Error('canonical snapshot did not advance component epoch: '+JSON.stringify(secondSnapshot));
  const second=await waitValue(cdp,`(()=>({label:document.getElementById('enduser-identity-label')?.textContent||'',facts:document.getElementById('enduser-identity-fingerprint')?.textContent||''}))()`,v=>v?.label==='iKant locale'&&v?.facts.includes('epoca 2')&&v?.facts.includes('model-b'),'component swap UI');
  const receipt={schema:'ikant-runtime-epoch-browser-liveness/v1-test',status:'PASS',real_browser_execution:true,production_surface_contract_js:true,production_enduser_js:true,identity_before:first.label,identity_after:second.label,epoch_after:secondSnapshot.ordinal,component_after:secondSnapshot.model,model_replacement_changed_identity:false};console.log(JSON.stringify(receipt));return receipt;
 }catch(error){throw new Error(`S17 browser epoch oracle failed: ${String(error?.message||error)}; browser=${berr}; fixture=${fx.err()}`);}finally{try{ws?.close();}catch{}chrome.kill('SIGKILL');fx.child.kill('SIGKILL');try{fs.rmSync(profile,{recursive:true,force:true});}catch{}}
}

if(import.meta.url===`file://${process.argv[1]}`){runRuntimeEpochBrowserLiveness().catch(error=>{console.error(JSON.stringify({schema:'ikant-runtime-epoch-browser-liveness/v1-test',status:'FAIL',error:String(error?.message||error)}));process.exitCode=1;});}
